# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 10:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180103_1557'),
    ]

    operations = [

    ]
