# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '找回密码')], max_length=16, verbose_name='类型'),
        ),
    ]
